title: NRBR Index
description: A radar-based index for burned area detection using Sentinel-1
theme: just-the-docs

baseurl: ""

search_enabled: true

nav_order:
  - Home
  - About NRBR
  - Methodology
  - Results
  - Downloads
  - Contact