site_name: Global Burn Scar Mapping with NRBR
site_author: Yonatan T.

plugins:
  - jekyll-spaceship

markdown: kramdown # Asegúrate de usar kramdown como procesador de Markdown

jekyll-spaceship:
  mathjax-processor:
    enable: true
    config:
      inline-math: [ ['$','$'], ['\\(','\\)'] ]
    
# Copyright
copyright: Copyright &copy; 2025 Yonatan Tarazona, Vasco Mantas and Courtney Schumacher

site_url: https://yotarazona.github.io/deeplearning_landcover/

theme:
    font:
        text: Roboto
    palette:
        - primary: black
        #- scheme: default # color por defecto
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    icon:
        repo: fontawesome/brands/github
    #logo: images/logo.png
    favicon: assets/favicon.png
    icon:
        logo: logo
    
    features:
        - navigation.sections
        - navigation.tabs # horizontal tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.integrate
    custom_dir: "docs/overrides"

#theme: readthedocs

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          #execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Welcome: index.md
    - Methodology: Methodology.md
    - Researches: Researches.md
    - Get Started: Get Started.md